### ISSUE TITLE
0.6.2 Appears to break editor window colour in Gruvbox Dark Hard

### ISSUE THREAD

**Issue by snus-kin** [lonre/gruvbox-intellij-theme#2]
Upon installing 0.6.2 my editor window is now light, other Dark themes are not affected.

**Comment by lonre** [comment]
Hi @snus-kin 

Apologies for the delayed response. Could you please check the 'Editor - Color Scheme' setting?

**Comment by snus-kin** [comment]
Hi, using v0.6.3 seems to work now, wondering if there was version mismatch between the plugin & the IDE I was experiencing. Couldn't say what I was doing Feb 9th :).

![Screenshot 2024-12-17 at 10 42 39](https://github.com/user-attachments/assets/41e215b0-7892-4c07-ac10-901a3ae92fa9)

I'll close this issue.
